version: "3"
services:
  runner:
    build: .
    volumes:
      - './conf.yml:/gickup/conf.yml'
      - '/home/andrew/.ssh/id_rsa:/gickup/id_rsa'
      - '/bigdisk/gickup:/backup'
    command: ["/gickup/app", "/gickup/conf.yml"]
